// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usb} from '../models';

export function GetHidList():Promise<usb.UsbList>;

export function SetHidBase():Promise<void>;
