// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHidList() {
  return window['go']['usb']['USB']['GetHidList']();
}

export function SetHidBase() {
  return window['go']['usb']['USB']['SetHidBase']();
}
