name: Wails build for linux

on:
  push:
    tags:
      # Match any new tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  PNPM_VERSION: "8"
  GO_VERSION: "1.22"

jobs:
  # 任务：构建
  build-linux:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [amd64, arm64]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # ubuntu 安装依赖
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0 upx-ucl

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ env.APP_NAME }}-${{matrix.platform}}
          build-platform: linux/${{ matrix.platform }}
          go-version: ${{ env.GO_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
