name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  PNPM_VERSION: "8"
  GO_VERSION: "1.21.8"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          [
            {
              name: "windows-amd64",
              platform: "windows/amd64",
              os: "windows-latest",
            },
            {
              name: "linux-amd64",
              platform: "linux/amd64",
              os: "ubuntu-latest",
            },
            {
              name: "linux-arm64",
              platform: "linux/arm64",
              os: "ubuntu-latest",
            },
            { name: "darwin-amd64", platform: "darwin/amd64", os: "macos-13" },
            { name: "darwin-arm64", platform: "darwin/arm64", os: "macos-13" },
          ]

    runs-on: ${{ matrix.build.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # set dependencies (linux only)
      - name: install dependencies (ubuntu only)
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-0 
          sudo apt-get install libwebkit2gtk-4.0-dev 
          sudo apt-get install gcc-aarch64-linux-gnu
          sudo apt-get install libusb-1.0
          sudo apt-get install upx

      # set dependencies (macos only)
      - name: install dependencies (macos only)
        if: matrix.build.os == 'macos-13'
        run: |
          brew install libusb
          brew install upx
          brew install mitchellh/gon/gon

      # set dependencies (windows only)
      - name: install dependencies (windows only)
        if: matrix.build.os == 'windows-latest'
        shell: powershell
        run: |
          choco install libusbdotnet
          choco install upx

      # Build UI
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build WebUI
        run: |
          cd frontend
          npm install
          npm run build

      # Build Wails
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: wails build -platform=${{matrix.build.platform}} -o=${{ env.APP_NAME }} -ldflags="-extldflags=-static -w -s"

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{ matrix.build.name }}
          path: |
            */bin/
            *\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */bin/*
