name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  # 任务：创建 release 版本
  # create-release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   outputs:
  #     RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Create Release
  #       id: create_release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')

  # 任务：构建
  build:
    permissions:
      contents: write
    # needs: create-release
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          # - name: "usb_list"
          #   platform: "linux/amd64"
          #   os: "ubuntu-latest"
          - name: "usb_list"
            platform: "windows/amd64"
            os: "windows-latest"
          # - name: "usb_list"
          #   platform: "darwin/amd64"
          #   os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # ubuntu 安装依赖
      - name: install dependencies (ubuntu only)
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0

      # macos 安装依赖
      - name: install dependencies (macos only)
        if: matrix.build.os == 'macos-latest'
        run: |
          brew install libusb

      # windows 安装依赖
      - name: install dependencies (windows only)
        if: matrix.build.os == 'windows-latest'
        shell: powershell
        run: |
          # 下载 libusb 压缩文件
          $url = 'https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.7z'
          $out = 'libusb.7z'
          Invoke-WebRequest -Uri $url -OutFile $out
          # 解压缩 libusb 文件
          7z x $out -oC:\libusb -r
          # 将 libusb 路径添加到环境变量中
          $env:Path = "C:\libusb\MinGW\bin;" + $env:Path

          # 下载 pkg-config 压缩文件
          $url = "https://win32builder.gnome.org/builds/pkg-config-lite/pkg-config-lite-latest.zip"
          $outfile = "pkg-config.zip"
          Invoke-WebRequest -Uri $url -OutFile $outfile
          Expand-Archive -Path $outfile -DestinationPath pkg-config
          Add-Path "$PWD/pkg-config/bin"

          pkg-config --libs libusb-1.0

      # 安装 pnpm
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      #     run_install: false

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.22"
          node-version: "20.1.0"
