name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  PNPM_VERSION: "8.10.0"
  GO_VERSION: "1.21"

jobs:
  # 任务：创建 release 版本
  # create-release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   outputs:
  #     RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Create Release
  #       id: create_release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')

  # 任务：构建
  build:
    permissions:
      contents: write
    # needs: create-release
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "linux-amd64"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "linux-arm64"
            platform: "linux/arm64"
            os: "ubuntu-latest"
          - name: "windows-amd64"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "macos-universal"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # ubuntu 安装依赖
      - name: install dependencies (ubuntu only)
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0 upx-ucl

      # macos 安装依赖
      - name: install dependencies (macos only)
        if: matrix.build.os == 'macos-latest'
        run: |
          brew install libusb upx

      # windows 安装依赖
      - name: install msys2 (windows only)
        if: matrix.build.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: "UCRT64"
          update: true
          release: false
      - name: install dependencies (windows only)
        if: matrix.build.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm --needed mingw-w64-ucrt-x86_64-gcc 
          pacman -S --noconfirm --needed mingw-w64-ucrt-x86_64-libusb 
          pacman -S --noconfirm --needed mingw-w64-ucrt-x86_64-pkg-config 
          pacman -S --noconfirm --needed mingw-w64-ucrt-x86_64-upx
      - name: set environment variables (windows only)
        if: matrix.build.os == 'windows-latest'
        shell: powershell
        run: |
          $env:Path+=";C:\msys64\usr\bin;C:\msys64\ucrt64"

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ env.APP_NAME }}-${{matrix.build.name}}
          build-platform: ${{ matrix.build.platform }}
          go-version: ${{ env.GO_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
