name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  # 任务：创建 release 版本
  # create-release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   outputs:
  #     RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Create Release
  #       id: create_release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')

  # 任务：构建
  build:
    permissions:
      contents: write
    # needs: create-release
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          # - name: "usb_list"
          #   platform: "linux/amd64"
          #   os: "ubuntu-latest"
          - name: "usb_list"
            platform: "windows/amd64"
            os: "windows-latest"
          # - name: "usb_list"
          #   platform: "darwin/amd64"
          #   os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # ubuntu 安装依赖
      - name: install dependencies (ubuntu only)
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0

      # macos 安装依赖
      - name: install dependencies (macos only)
        if: matrix.build.os == 'macos-latest'
        run: |
          brew install libusb

      # windows 安装依赖
      - name: install msys2 (windows only)
        if: matrix.build.os == 'windows-latest'
        uses: msys2/setup-msys2@v2

      - name: install dependencies (windows only)
        if: matrix.build.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S mingw-w64-x86_64-gcc
          pacman --noconfirm -S mingw-w64-x86_64-libusb
          pacman -Ql mingw-w64-x86_64-libusb
          pacman --noconfirm -S mingw-w64-x86_64-pkg-config
          pkg-config --cflags libusb-1.0
          pkg-config --libs libusb-1.0

      - name: setup windows env
        if: matrix.build.os == 'windows-latest'
        shell: powershell
        run: |
          $env:PATH += ";C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\tools\msys64"
          echo $env:PATH

      - name: Cache Go dependencies
        id: cache-go-deps
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.22"
          node-version: "20.1.0"
