on:
  push:
    tags:
      # Match any new tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  PNPM_VERSION: "8"
  GO_VERSION: "1.22"

permissions:
  contents: write
  packages: write

jobs:
  # 任务：构建
  build-linux:
    name: app build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ubuntu 安装依赖
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config
          sudo apt-get install -y libusb-1.0 
          sudo apt-get install -y upx-ucl
          sudo apt-get install -y libgtk-3-dev
          sudo apt-get install -y libwebkit2gtk-4.0-dev

      # 前端打包
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{env.PNPM_VERSION}}
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: |
          cd frontend
          pnpm install
          pnpm run build

      # go 后端编译
      - name: Wails Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: ${{ env.APP_NAME }}
          pre_command: "go install github.com/wailsapp/wails/v2/cmd/wails@latest"
          build_command: 'wails build -s -upx -platform="${{ matrix.goos }}/${{ matrix.goarch }}" -webview2=download -ldflags="-extldflags=-static -w -s -H windowsgui"'
          compress_assets: OFF
          goversion: ${{ env.GO_VERSION }}
