on:
  push:
    tags:
      # Match any new tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  PNPM_VERSION: "8"
  GO_VERSION: "1.22"

permissions:
  contents: write
  packages: write

jobs:
  # 任务：构建
  build-linux:
    name: app build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        exclude:
          [
            { os: windows, arch: arm64 },
            { os: darwin, arch: arm64 },
            { os: darwin, arch: amd64 },
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 前端打包
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{env.PNPM_VERSION}}
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - name: Build WebUI
        run: |
          cd frontend
          pnpm install
          pnpm run build

      # go 后端编译
      - name: Wails Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          binary_name: ${{ env.APP_NAME }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          pre_command: |
            go install github.com/wailsapp/wails/v2/cmd/wails@latest
            && wails doctor
            && apt-get install -y pkg-config libusb-1.0-0-dev upx-ucl libgtk-3-dev libwebkit2gtk-4.0-dev
          build_command: wails build -s -upx -webview2=download
          build_flags: -platform=${{ matrix.os }}/${{ matrix.arch }}
          ldflags: "-extldflags=-static -w -s"
          compress_assets: OFF
          goversion: ${{ env.GO_VERSION }}
