name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  APP_NAME: "usb_list"
  NODE_OPTIONS: "--max-old-space-size=4096"
  NODE_VERSION: "20"
  # PNPM_VERSION: "8.10.0"
  GO_VERSION: "1.21.8"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "windows-amd64"
            platform: "windows/amd64"
            os: "windows-latest"

    runs-on: ${{ matrix.build.os }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # windows 安装依赖
      - name: install msys2 (windows only)
        if: matrix.build.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: "UCRT64"
          update: true
          release: false
          install: >-
            mingw-w64-ucrt-x86_64-go
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-upx
            mingw-w64-ucrt-x86_64-libusb

      # 前端打包
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: cd frontend && npm install && npm run build

      # 编译
      - name: Build wails (windows only)
        if: matrix.build.os == 'windows-latest'
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          wails build -s -platform="${{ matrix.build.platform }}" -webview2=download  -ldflags="-extldflags=-static -w -s" -o ${{ env.APP_NAME }}-${{matrix.build.name}}
      - name: Build wails (linux & macos)
        if: matrix.build.os != 'windows-latest'
        run: |
          wails doctor
          wails build -s -platform="${{ matrix.build.platform }}" -ldflags="-extldflags=-static -w -s" -o ${{ env.APP_NAME }}-${{matrix.build.name}}

      # 发布 release
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{matrix.build.name}}
          path: |
            */bin/
            *\bin\*
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */bin/*
